[project]
name = "openfoodfacts"
version = "2.7.0"
authors = [
    {name = "The Open Food Facts team", email = "contact@openfoodfacts.org"}
]
description = "Official Python SDK of Open Food Facts"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
dependencies = [
    "requests>=2.20.0",
    "pydantic>=2.0.0,<3.0.0",
    "tqdm>=4.0.0,<5.0.0",
]
dynamic = ["classifiers"]

[tool.poetry]
include = [
    {path = "tests", format = "sdist"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.urls]
repository = "https://github.com/openfoodfacts/openfoodfacts-python"

[tool.mypy]
ignore_missing_imports = true

[tool.isort] # From https://black.readthedocs.io/en/stable/compatible_configs.html#isort
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
redis = { version = "~5.1.0", optional = true, extras = ["hiredis"] }
Pillow = { version = ">=9.3,<11", optional = true }
tritonclient = {extras = ["grpc"], version = ">2.0.0,<3.0.0", optional = true}
opencv-python-headless = {version = ">4.0.0,<5.0.0", optional = true}

[tool.poetry.group.dev.dependencies]
requests-mock = "1.11.0"
flake8 = "6.0.0"
black = "24.3.0"
mypy = "1.12.0"
isort = "5.12.0"
coverage = {version = "7.2.7", extras = ["toml"]}
pytest = "7.4.2"
types-requests = "2.31.0.2"
types-tqdm = "4.66.0.20240417"
types-redis = "^4.6.0.20240425"

[project.optional-dependencies]
redis = ["redis"]
pillow = ["Pillow"]
ml = ["tritonclient[grpc]", "opencv-python-headless", "Pillow"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
