[project]
name = "snailz"
description = "Synthetic data generator for snail mutation survey"
keywords = ["open science", "synthetic data"]
readme = "README.md"
authors = [
    { name = "Greg Wilson", email = "gvwilson@third-bit.com" }
]

version = "3.0.0"
requires-python = ">=3.12"
dependencies = [
    "faker",
    "pydantic"
]

[project.optional-dependencies]
dev = [
    "build",
    "coverage",
    "griffe-fieldz",
    "markdown-include",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "pytest",
    "ruff",
    "twine"
]

[project.urls]
home = "https://github.com/gvwilson/snailz"

[project.scripts]
snailz = "snailz.main:main"

[tool.setuptools]
packages = ["snailz"]

[tool.uv]
package = true
