[project]
authors = [
    {name = "Eetu Mäkelä", email = "eetu.makela@helsinki.fi"},
]
license = {text = "MIT"}
requires-python = "<4.0,>=3.10"
dependencies = [
    "lxml>=5",
    "click>=8",
    "tqdm>=4",
    "hsciutil>=0.1.2",
    "fsspec>=2025",
    "pyarrow>=20",
    "s3fs>=2025",
    "zstandard>=0.23.0",
]
name = "bibxml2"
version = "1.5.1"
description = "A simple converter of MARCXML/PICAXML to CSV/TSV/parquet"
readme = "README.md"
keywords = [
    "MARCXML",
    "PICA XML",
    "bibliographic data",
    "data conversion",
]

[project.urls]
repository = "https://github.com/hsci-r/bibxml2"

[project.scripts]
bibxml2 = "bibxml2.bibxml2:convert"

[dependency-groups]
dev = [
    "pytest>=8",
]
