[project]
name = "nuvemshop-client-python"
version = "0.2.1" # Incremente a versÃ£o
description = "Um cliente Python robusto e intuitivo para a API da Nuvemshop."
readme = "README.md"
requires-python = ">=3.13"
authors = [
  { name="Bruno Vidal", email="brunovidal@lojabibelo.com.br" },
]


dependencies = [
    "decouple>=0.0.7",
    "flask>=3.1.1",
    "requests>=2.32.3",
    "twine>=6.1.0",
]
[tool.setuptools]
package-dir = {"" = "src"}

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
