[package]
name = "rtest-core"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
glob = "0.3"
regex = "1.10"
ruff_python_parser = { path = "../ruff/crates/ruff_python_parser" }
ruff_python_ast = { path = "../ruff/crates/ruff_python_ast" }
num_cpus = "1.0"
log = "0.4"

[dev-dependencies]
tempfile = "3.0"
