[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "partix"
version = "0.1.4"
description = "A minimal test package for publishing to PyPI"
authors = [
    { name="HJH", email="me@example.com" }
]
license = { text="MIT" }
dependencies = [
    "antlr4-python3-runtime>=4.11,<5",
    "jsonpath_ng==1.7.0"
]

[project.urls]
Homepage = "https://example.igrashiyouma.com"
