[tool.poetry]
name = "chatty-shell"
version = "0.2.0"
description = ""
authors = ["Artur Dernst <artur@dernst.me>"]

[tool.poetry.dependencies]
python = "^3.10"
langgraph = "^0.5.1"
langchain = "^0.3.26"
langchain-community = "^0.3.27"
langchain-openai = "^0.3.27"
pyperclip = "^1.9.0"

[[tool.poetry.packages]]
include = "chatty_shell"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
chat = "chatty_shell.main:main"
