[project]
name = "libtorrent-windows-dll"
version = "0.0.3"
description = "Required Windows OpenSSL DLLs for libtorrent"
readme = "README.md"
license = "MIT"
requires-python = ">=3.7"
dependencies = ["libtorrent>=2.0.11"]
authors = [
    { name = "baseplate-admin", email = "61817579+baseplate-admin@users.noreply.github.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.urls]
Documentation = "https://github.com/baseplate-admin/libtorrent-windows-dll#readme"
Issues = "https://github.com/baseplate-admin/libtorrent-windows-dll/issues"
Source = "https://github.com/baseplate-admin/libtorrent-windows-dll"

[dependency-groups]
build = ["hatch>=1.14.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["src/libtorrent"]
