
[package]
name = "rtest"
version = "0.0.18"
edition = "2021"

[lib]
name = "rtest"
crate-type = ["cdylib"]

[[bin]]
name = "rtest"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rtest-core = { path = "rtest-core" }
pyo3 = { version = "0.25", features = ["extension-module"] }
clap = { version = "4.5.4", features = ["derive"] }

[dev-dependencies]
tempfile = "3.0"
