[tool.poetry]
name = "performance-catcher"
version = "2.1.0"
description = "Android Performance Toolkit"
authors = ["kaluluosi111 <kaluluosi@gmail.com>"]
repository = "https://github.com/kaluluosi/performance-catcher"
license = "MIT"
readme = "README.md"

packages = [{include="perfcat",from="src"}]

[tool.poetry.scripts]
perfcat = "perfcat:run"

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
nicegui = "^2.20.0"
reactivex = "^4.0.4"
pywebview = "^5.4"
pydantic = "^2.11.7"
pydantic-settings = "^2.9.1"
toml = "^0.10.2"
async-adbc = "1.1.2"
html2image = "^2.0.7"


[tool.poetry.group.dev.dependencies]
ruff = "^0.11.13"
pyinstaller = "^6.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
