# This file should be in the future instead of setup.py
# https://python-poetry.org/docs/pyproject

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "messages-local"
version = "0.0.1" # https://pypi.org/project/messages-local
description = "messages-local Python Package"
readme = "README.md"
authors = [
    "Circlez.ai <info@circlez.ai>",
]
