[project]
name = "asktable-mcp-server"
version = "0.2.22"
description = "asktable_mcp_server project"
readme = "README.md"
authors = [
    { name = "chenchengfeng", email = "carlos12014@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "asktable>=5.4.0",
    "fastmcp>=2.8.0",
    "aiohttp>=3.9.0"
]

[project.scripts]
asktable-mcp-server = "asktable_mcp_server.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
