[project]
name = "doloris"
version = "0.2.0"
description = "Detection Of Learning Obstacles via Risk-aware Interaction Signals"
authors = [
    { name = "许睿林", email = "xurlin5@mail2.sysu.edu.cn" },
    { name = "傅小桐", email = "fuxt5@mail2.sysu.edu.cn" }
]

readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

requires-python = ">=3.8"
dependencies = [
    "gradio",
    "pandas",
    "tqdm"
]

[project.scripts]
doloris = "doloris.__main__:main"

[tool.setuptools]
packages = ["doloris"]