[build-system]
requires = ['setuptools>=61.0']
build-backend = 'setuptools.build_meta'

[project]
name = 'secretrandom'
version = 'v2.2.2'
description = 'Unpredictable random number generation and character generation (random + secrets module combined).'
readme = 'README.md'
requires-python = '>=3.11'
license = "MIT"
authors = [
  {name = 'dUhEnC-39', email = 'albeback01@gmail.com'}
]


[tool.setuptools.packages.find]
where = ['src']
