[tool.poetry]
name = "tkfluent"
version = "0.1.5"
description = "Fluent(SunValley) Design for Tkinter. Modern GUI"
authors = ["XiangQinxi <xiangqinxi@outlook.com>"]
readme = "README.md"
documentation = "https://tkfluent.netlify.app"
packages = [
    { include = "tkflu" }
]
license = "GPL-3.0"
keywords = [ "tkfluent", "tksvg", "tkinter", "fluent", "modern", "GUI", "interface" ]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: MacOS X",
    "Environment :: Win32 (MS Windows)",
    "Environment :: X11 Applications",
    "Natural Language :: Chinese (Simplified)",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Tcl",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.8"
tksvg = "^0.7.4"
tkextrafont = "^0.6.3"
svgwrite = "^1.4.3"
pillow = "^10.2.0"
tkdeft = "0.1.1"
easydict = "^1.13"
numpy = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
