[project]
name = "pytuneblade"
version = "0.1.1"
description = "A Python interface to control TuneBlade remotely, built for Home Assistant integrations"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
  { name = "spycle", email = "spycle@users.noreply.github.com" }
]
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
