[project]
name = "sunweather"
version = "1.2.2"
description = ""
authors = [
    {name = "DJ Stomp",email = "85457381+DJStompZone@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tqdm (>=4.67.1,<5.0.0)",
    "pillow (>=11.3.0,<12.0.0)",
    "httpx[http2] (>=0.28.1,<0.29.0)",
    "numpy (>=2.3.1,<3.0.0)",
    "ffmpeg (>=1.4,<2.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
sunweather = "sunweather.__main__:main"
