[package]
name = "nessie_py"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "nessie_py"
crate-type = ["cdylib"]

[dependencies]
fof = "0.1.5"
pyo3 = "0.25.0"
rayon = "1.10.0"
