[project]
name = "fyuneru"
version = "0.1.4"
description = "A Python utility library with logging and path management"
authors = [{name = "inklov3", email = "inklov3@163.com"}]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "loguru >=0.7.3",
    "pathlib >=1.0.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
