[project]
name = "werkdone-excel-server"
version = "1.1.11"
description = "MCP Excel Tool Server for generating visitation reports"
authors = [{name = "Obie Ananda", email = "Obie.kal22@gmail.com"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.10.1",
    "openpyxl>=3.1.5",
    "smolagents[mcp]>=1.19.0",
    "twine>=6.1.0",
]

[project.scripts]
werkdone-excel-server = "werkdone_excel_server.server:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]