[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["gh"]

[tool.hatch.build]
sources = ["src"]

[project]
name = "gambozino-hunter"
version = "1.0.8"
dependencies = [
	"nvdlib==0.8.0",
	"click==8.2.1",
	"markdown-it-py==3.0.0",
	"mdurl==0.1.2",
	"Pygments==2.19.1",
	"rich==14.0.0",
	"shellingham==1.5.4",
	"typer==0.16.0",
	"typing_extensions==4.14.0",
	"IPy==1.1",
	"scapy==2.6.1",
]
requires-python = ">=3.8"
authors = [
  {name = "Filipe Silva", email = "pradyun@example.com"},
  {name = "Hugo Almeida", email = "tzu-ping@example.com"},
]
maintainers = [
  {name = "Filipe Silva", email = "pradyun@example.com"},
]
description = "Network and Vulnerability scanner"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]
keywords = ["network", "cve", "cpe", "vulnerability", "scanner"]
classifiers = [  
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python"
]

[project.urls]
# Homepage = "https://example.com"
# Documentation = "https://readthedocs.org"
Repository = "https://github.com/ScriptK-dd13s/GambozinoHunter"
"Bug Tracker" = "https://github.com/ScriptK-dd13s/GambozinoHunter/issues"
# Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[project.scripts]
gh = "gh.cli:app"
