[project]
name = "git-rb"
version = "0.1.2"
description = "Simple CLI for interactive git rebase workflow."
authors = [{ name = "George Lenton", email = "georgelenton@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = "==3.13.4"
keywords = ["git", "rebase", "workflow"]
dependencies = [
    "rich>=14.0.0",
]

[project.urls]
Homepage = "https://github.com/geo7/git-rb"
Repository = "https://github.com/geo7/git-rb"

[project.scripts]
git-rb = "git_rb.main:main"

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0,<9.0.0",
    "pre-commit>=4.0.0",
    "ipython>=8.18.1",
    "ipdb>=0.13.9,<0.14.0",
    "ruff>=0.0.265",
    "pytest-cov>=5.0.0",
    "pdbpp>=0.10.3,<0.12.0",
    "ty>=0.0.1a13",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN204",   #  Missing return type annotation for special method `__attrs_post_init__`
    "ANN206",   #  Missing return type annotation for classmethod `get_all_human_readable`
    "D100",     #  Missing docstring in public module
    "D101",     #  Missing docstring in public class
    "D102",     #  Missing docstring in public method
    "D103",     #  Missing docstring in public function
    "D104",     #  Missing docstring in public package
    "D105",     #  Missing docstring in magic method
    "D107",     #  Missing docstring in `__init__`
    "D203",     #  Conflicts with formatter
    "D211",     #  no-blank-line-before-class
    "D212",     #  multi-line-summary-first-line
    "D401",     #  First line of docstring should be in imperative mood.
    "FIX002",   #  Line contains TODO, consider resolving the issue
    "COM812",   #  missing-trailing-comma
    "ISC001",   #  single-line-implicit-string-concatenation
    "PD901",    #  `df` is a bad variable name.
    "PLR0913",  #  Too many arguments to function call (6 > 5)
    "PLW1510",  #  `subprocess.run` without explicit `check` argument
    "PTH123",   #  `open()` should be replaced by `Path.open()`
    "PTH201",   #  [*] Do not pass the current directory explicitly to `Path`
    "RUF010",   #  [*] Use explicit conversion flag
    "S311",     #  Standard pseudo-random generators are not suitable for cryptographic purposes
    "S603",     #  `subprocess` call: check for execution of untrusted input
    "S101",     # Use of `assert` detected
    "T100",     #  Trace found: `breakpoint` used
    "T201",     #  `print` found
]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"scratch/*" = ["ALL"]
"tests/*" = [
    "ANN001",  #  Missing type annotation for function argument `tmpdir`
    "ANN201",  #  Missing return type annotation for public function `test_get_file_types`
    "ARG001",  # Unused function argument: `mock_prompt_ask`
    "D100",    #  Missing docstring in public module
    "D101",    #  Missing docstring in public class
    "D102",    #  Missing docstring in public method
    "D205",    # 1 blank line required between summary line and description
    "S101",    #  Use of `assert` detected
    "S607",    # Starting a process with a partial executable path
]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
case-sensitive = true
combine-as-imports = true
