[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "linuxboost"
version = "0.1.0"
description = "A GUI app to quickly install Linux apps and commands"
authors = [{ name="Priyanshu Raj", email="prmahatha@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.7"
dependencies = ["PyQt5"]

[project.scripts]
linuxboost = "main:main"

[tool.setuptools]
packages = ["linuxboost"]
include-package-data = true
