[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"

[project]
name =  "wovodat"
version = "0.0.2"
authors = [
    {name = "Martanto", email = "martanto@live.com"},
]
description = "Unofficial WOVOdat python package. WOVOdat is a comprehensive global database on volcanic unrest."
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["wovodat", "volcano", "data", "observatory", "volcanoes", "volcanic", "unrest", "forecast"]
requires-python = ">=3.10"
dependencies = [
    "gvp>=0.0.3",
    "openpyxl>=3.1.5",
    "pandas>=2.2.2",
    "numpy>=2.2.5",
    "matplotlib>=3.9.0",
    "peewee>=3.17.5",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
base = [
    "gvp",
    "openpyxl",
    "pandas",
    "numpy",
    "matplotlib",
    "peewee",
]

[project.urls]
Homepage = "https://github.com/martanto/wovodat-python"
Issues = "https://github.com/martanto/wovodat-python/issues"