[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yby6-parse-video-mcp"
version = "0.1.4"
description = "A video parsing toolkit."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
  {name = "yangbuyiya", email = "yangbuyiya@duck.com"}
]
dependencies = [
  "fastapi",
  "pydantic>=2.11.7",
  "python-dotenv>=1.1.0",
  "httpx>=0.28.1",
  "starlette==0.37.2",
  "rich>=13.9.4",
  "fastmcp==2.10.2"
]

[project.scripts]
yby6-parse-video-mcp = "mcp_server:main"

[project.urls]
"Homepage" = "https://yby6.com"
"Repository" = "https://github.com/yangbuyiya/parse-video-py"

[tool.setuptools.packages.find]
include = ["parser*", "keys*", "utils*"]

[tool.setuptools]
py-modules = ["mcp_server", "main"] 