[project]
name = "catscrape"
version = "1.2.0"
description = "A Python library with functions to scrape data from Scratch.mit.edu"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.12"
license = { file = "LICENSE" }
authors = [
    { name = "Atticus Alarcon", email = "atticusaalarcon@gmail.com" }
]
keywords = ["scratch", "api", "web", "scraping"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
  "requests>=2.32.4",
  "appdirs>=1.4.4",
  "numpy>=2.3.0",
  "selenium>=4.34.0",
  "webdriver-manager>=4.0.2"
]

[project.urls]
"Homepage" = "https://github.com/att131/catscrape"
"Bug Tracker" = "https://github.com/att131/catscrape/issues"
"Source" = "https://github.com/att131/catscrape"
"Documentation" = "https://github.com/att131/catscrape#readme"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"