[tool.poetry]
name = "dbx-hpexts"
version = "0.1.17"
description = "Databricks helpers and extensions"
authors = ["francisco javier larios <fjlsoto@gmail.com>"]
readme = "README.md"
packages = [
    {from = 'src',  include = 'dbx_hpexts'}
]

[tool.poetry.dependencies]
python = "^3.10"
hcp-vault-secrets-wrapper = "^0.7.5"
pyspark = "^4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
