[project]
name = "oxigrad"
version = "0.2.1"
description = "A minimal scalar-valued autograd engine written in Rust"
readme = { file = "README.pypi.md", content-type = "text/markdown" }
license = { text = "MIT" }
authors = [{ name = "lalitm1004", email = "lalitm1004@gmail.com" }]
requires-python = ">=3.9"
dependencies = []

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[project.urls]
Repository = "https://github.com/lalitm1004/oxigrad"
Homepage = "https://github.com/lalitm1004/oxigrad"
Issues = "https://github.com/lalitm1004/oxigrad/issues"


[project.scripts]
micrograd-rs = "oxigrad:main"

[tool.maturin]
module-name = "oxigrad._core"
python-packages = ["oxigrad"]
python-source = "src"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
