[project]
name = "wyrmx-cli"
version = "1.0.12"
description = "Wyrmx CLI is the official command-line interface for Wyrmx â€” a blazing-fast, Cython-accelerated, AI-enhanced web framework built on FastAPI."
authors = [
    {name = "Yousri Aouledissa",email = "aouledissayousri@gmail.com"}
]

license = {text = "MIT"}
readme = "README.md"
#requires-python = ">3.9.0,<3.9.1 || >3.9.1,<4.0"
requires-python = ">=3.9,!=3.9.1,<4.0"


dependencies = [
    "anyio (>=4.9.0,<5.0.0)",
    "build (>=1.2.2.post1,<2.0.0)",
    "cachecontrol (>=0.14.3,<0.15.0)",
    "certifi (>=2025.4.26,<2026.0.0)",
    "cffi (>=1.17.1,<2.0.0)",
    "charset-normalizer (>=3.4.2,<4.0.0)",
    "cleo (>=2.1.0,<3.0.0)",
    "crashtest (>=0.4.1,<0.5.0)",
    "cryptography (>=45.0.3,<46.0.0)",
    "distlib (>=0.3.9,<0.4.0)",
    "dulwich (>=0.22.8,<0.23.0)",
    "fastjsonschema (>=2.21.1,<3.0.0)",
    "filelock (>=3.18.0,<4.0.0)",
    "findpython (>=0.6.3,<0.7.0)",
    "h11 (>=0.16.0,<0.17.0)",
    "httpcore (>=1.0.9,<2.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "idna (>=3.10,<4.0)",
    "installer (>=0.7.0,<0.8.0)",
    "jaraco-classes (>=3.4.0,<4.0.0)",
    "jaraco-context (>=6.0.1,<7.0.0)",
    "jaraco-functools (>=4.1.0,<5.0.0)",
    "jeepney (>=0.9.0,<0.10.0)",
    "keyring (>=25.6.0,<26.0.0)",
    "more-itertools (>=10.7.0,<11.0.0)",
    "msgpack (>=1.1.0,<2.0.0)",
    "packaging (>=25.0,<26.0)",
    "pbs-installer (>=2025.5.17,<2026.0.0)",
    "pkginfo (>=1.12.1.2,<2.0.0.0)",
    "platformdirs (>=4.3.8,<5.0.0)",
    "poetry (>=2.1.3,<3.0.0)",
    "poetry-core (>=2.1.3,<3.0.0)",
    "pycparser (>=2.22,<3.0)",
    "pyproject-hooks (>=1.2.0,<2.0.0)",
    "rapidfuzz (>=3.13.0,<4.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "requests-toolbelt (>=1.0.0,<2.0.0)",
    "secretstorage (>=3.3.3,<4.0.0)",
    "shellingham (>=1.5.4,<2.0.0)",
    "sniffio (>=1.3.1,<2.0.0)",
    "tomlkit (>=0.13.2,<0.14.0)",
    "trove-classifiers (>=2025.5.9.12,<2026.0.0.0)",
    "urllib3 (>=2.4.0,<3.0.0)",
    "virtualenv (>=20.31.2,<21.0.0)",
    "zstandard (>=0.23.0,<0.24.0)",
    "typer (>=0.16.0,<0.17.0)",
    "fastapi (>=0.116.0,<0.117.0)",
    "uvicorn (>=0.35.0,<0.36.0)"

]

[[tool.poetry.packages]]
include = "wyrmx"

[tool.poetry.scripts]
wyrmx = "wyrmx.main:app"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
