[build-system]
requires = ["setuptools>=61.0", "numpy<2", "nltk", "scikit-learn", "fasttext", "model2vec", "faiss-cpu", "bm25s"]
build-backend = "setuptools.build_meta"

[project]
name = "strive_ranker"
version = "2.33"
authors = [
  { name="Carlo Moro", email="cnmoro@gmail.com" },
]
description = ""
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy<2",
    "nltk",
    "scikit-learn",
    "fasttext",
    "model2vec",
    "faiss-cpu",
    "bm25s"
]
