[package]
name = "sayaka"
version = "0.6.6"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sayaka"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.1"
memmap2 = "0.9.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
base64 = "0.22.1"
