[project]
name = "ns-docker-wrapper"
version = "0.1.2"
description = "Run Nerfstudio inside docker as a python package"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Jour de Lune", email = "jourdelune863@gmail.com"},
]
dependencies = [
    "docker>=7.1.0",
    "pycolmap>=3.12.1",
]

[project.urls]
"Homepage" = "https://github.com/jourdelune/ns_docker_wrapper"
"Repository" = "https://github.com/jourdelune/ns_docker_wrapper"
"Documentation" = "https://jourdelune.github.io/ns_docker_wrapper/"
