[project]
name = "envkit"
version = "0.3.1"
description = "A lightweight package for parsing environment variables."
authors = [{ name = "Theo Guerin", email = "contact@theo-guerin.dev" }]
readme = "README.md"

requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = ["ruff>=0.12.2", "pyright>=1.1.402", "basedpyright>=1.29.5"]

[build-system]
requires = ["uv_build>=0.7.19,<0.8.0"]
build-backend = "uv_build"

[tool.basedpyright]
typeCheckingMode = "strict"
