[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "streamlit-google-picker"
version = "0.2.5"
description = "Streamlit component for picking files from Google Drive"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "streamlit>=1.45.0",
]
authors = [
    {name = "Lounes Allioui", email = "hello@lounesallioui.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.optional-dependencies]
oauth = [
    "python-dotenv>=1.0.1",
    "streamlit-oauth>=0.1.14",
]
dev = [
    "pytest>=8.4.1",
    "playwright>=1.53.0",
    "setuptools>=80.9.0",
]

[tool.setuptools]
include-package-data = true
packages = ["streamlit_google_picker"]
