[menu.drun]
label="Desktop Run Menu (drun)"
exec="wofi --show=drun --height=80% --width=70%" 
search_tags="utility,launch,wofi"

[menu.run]
label="Run Menu"
exec="wofi --show=run --height=80% --width=70%"
search_tags="utility,wofi"

[colorpicker]
label="Color Picker"
exec="hyprpicker"
sleep_before=0.3
search_tags="utility,hyprpicker"
show_response=true

