[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "magentism"
version = "0.2.6"
description = "A lightweight framework for LLM-based agents with database persistency"
requires-python = ">=3.12"
authors = [
    {name = "Mathieu Rodic"},
]
keywords = ["LLM", "agent", "persistence"]
license = {text = "MIT"}
classifiers = [
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "ormantism>=0.2.4",
    "langchain>=0.3.26",
    "markdownify>=1.1.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["magentism"]

[tool.setuptools.package-data]
magentism = ["magentism.cpython-312-x86_64-linux-gnu.so"]
