[package]
name = "oxigrad"
version = "0.2.2"
edition = "2021"
description = "A minimal scalar-valued autograd engine written in Rust"
license = "MIT"
repository = "https://github.com/lalitm1004/oxigrad"
homepage = "https://github.com/lalitm1004/oxigrad"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.4", features = ["extension-module", "abi3-py39"] }
