[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pentago"
version = "0.1.3"
description = "Unofficial Papago API using reverse-engineered web endpoints"
readme = "README.md"
requires-python = ">=3.6"
license = { text = "MIT" }
authors = [
    { name = "Klypse" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]

[project.urls]
Homepage = "https://github.com/Klypse/PentaGo"
Repository = "https://github.com/Klypse/PentaGo"