 
[project]
name = "arcade-ytx"
version = "1.2"
description = "ğŸ˜ Bring back retro arcade vibes with this Python game pack! All addictive gameplay built with love (and the rich library)."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [
  { name = "Aryan Kalra", email = "aryan.kalra363@gmail.com" }
]
keywords = ["arcade", "games", "terminal", "rich", "python"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

dependencies = [
  "markdown-it-py==3.0.0",
  "mdurl==0.1.2",
  "Pygments==2.19.2",
  "rich==14.0.0",
  "pyfiglet"
]

[project.urls]
Homepage = "https://github.com/A-ryan-Kalra/arcade-ytx/tree/feat/all-game"

[project.scripts]
arcade-ytx = "arcade_ytx.main:run_game"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"



 