[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "differintP"
version = "0.0.4"
description = "Modern, pure Python fractional calculus library (fork of differint)"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "iparsw", email = "parsaroshanak@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Mathematics",
]
dependencies = [
    # Add your runtime dependencies here, example:
    "numpy>=1.19",
    "scipy>=1.15.3",
    "numba>=0.61.2"
]

[project.optional-dependencies]
gpu = [
    "cupy"
]

[project.urls]
Homepage = "https://github.com/iparsw/differintP"
Repository = "https://github.com/iparsw/differintP"
Issues = "https://github.com/iparsw/differintP/issues"



[tool.setuptools.packages.find]
where = ["."]
include = ["differintP*"]

