[tool.poetry]
name = "mulch"
version = "0.1.22"
description = "Workspace Factory CLI for initializing standard workspace folders"
authors = ["George Clayton Bennett <george.bennett@memphistn.gov>"]
packages = [{ include = "mulch", from = "src" }]
include = [
	"src/mulch/scaffold.json",
	#"src/mulch/secrets.yaml",
	"src/mulch/secrets-example.yaml",
	"default-workspace.toml",
	"default-config.toml",
	"src/mulch/templates/*.j2"
	]  # This must be a list # This tells poetry to package scaffold.json
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
toml = "^0.10.2"
typer = "^0.12.3"
click = "<8.1.7"
rich = "<13.7.0"
jinja2 = "^3.1.6"

[tool.poetry.scripts]
mulch = "mulch.cli:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
