[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tinytrie"
version = "0.1.0a0"
description = "A minimal type-safe trie (prefix tree) implementation in Python."
readme = "README.md"
requires-python = ">=2"
license = "MIT"
authors = [
  { name="Jifeng Wu", email="jifengwu2k@gmail.com" }
]
keywords = ["trie", "prefix tree", "data structure", "python"]
classifiers = [
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jifengwu2k/tinytrie"
"Bug Tracker" = "https://github.com/jifengwu2k/tinytrie/issues"
