[build-system]
requires = ["setuptools==80.9.0", "setuptools-scm>=8.2.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "diamond-shovel"
description = "A high-performance task-processing framework designed for cybersecurity"
readme = "README.md"
requires-python = ">=3.13"
license = "LGPL-3.0-only"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Programming Language :: Python :: 3",
    "Topic :: Security",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: OS Independent",
    "Framework :: FastAPI",
    "Framework :: AsyncIO",
]
keywords = [
    "cybersecurity",
    "task processing",
    "asynchronous",
    "fastapi",
    "python",
    "framework",
]
authors = [
    {email = "shovel@hscsec.cn"}
]
maintainers = [
    {email = "shovel@hscsec.cn"}
]
dependencies = [
    "annotated-types==0.7.0",
    "anyio==4.9.0",
    "click==8.2.1",
    "colorlog==6.9.0",
    "dill==0.4.0",
    "fastapi==0.115.12",
    "h11==0.14.0",
    "idna==3.10",
    "kink==0.8.1",
    "pydantic==2.11.5",
    "sniffio==1.3.1",
    "typing-inspection==0.4.0",
    "typing_extensions==4.14.0",
    "uvicorn==0.34.0",
    "websockets==15.0.1",
    "python-multipart~=0.0.20",
    "cryptography==45.0.4"
]

[tool.setuptools_scm]
version_file = "diamond_shovel/version.py"
local_scheme = "no-local-version"

[project.urls]
Homepage = "https://www.hscsec.cn"
Documentation = "https://diamond-shovel.github.io/shovel-wiki/"
Repository = "https://github.com/diamond-shovel/diamond-shovel"
Issues = "https://github.com/diamond-shovel/diamond-shovel/issues"

[project.scripts]
diamond-shovel = "diamond_shovel.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["diamond_shovel*"]
exclude = ["diamond_shovel.tests*"]

