[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "spectroplot"
version = "0.0.3"
dependencies = [
    "pandas~=2.2.3",
    "matplotlib~=3.9.2",
    "numpy~=2.1.3",
    "openpyxl~=3.1.5",
]
requires-python = ">=3.12"
authors = [
    {name = "Bakyt-Bek Murzabaev", email = "b.b.murzabaev@gmail.com"},
]
description = "A Python class for plotting frequency overlaps."
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]
keywords = ["spectrum", "frequency", "plot",]
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: Microsoft :: Windows",
]

[project.urls]
Homepage = "https://github.com/murzabaevb/spectroplot"
Issues = "https://github.com/murzabaevb/spectroplot/issues"