[tool.poetry]
name = "airflow-operators"
version = "0.10.0"
description = "Custom operators for Apache Airflow"
authors = ["Anonymous"]
license = "MIT"
readme = "README.md"
packages = [{include = "airflow_operators", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9"
apache-airflow-providers-apache-kafka = "^1.5.0"
apache-airflow-providers-mysql = "^5.5.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
