[project]
name = "lumera"
version = "0.1.1"
description = "Lumera library"
requires-python = ">=3.8"
dependencies = [
    "requests",
    "python-dotenv",
]

[tool.setuptools]
py-modules = ["lumera"]   # <- single file lumera.py
