[project]
name = "elara-wrapper"
version = "0.0.3"
description = "A FastAPI middleware package to validate requests to Elara agents based on the permissions set in their ENS name."
authors = []
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "fastapi[standard] (>=0.115.14,<0.116.0)",
    "pydantic (>=2.11.7,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
mypy = "^1.16.1"
ruff = "^0.12.2"

