[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SCINApy"
version = "0.1.1"  # Updated version to fix bug
description = "A Python package for semi-supervised cell type identification and assignment using scRNA-seq and Cytof/FACS data."
authors = [{name = "Han Wenrui", email = "hwr9912@gmail.com"}]
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "numpy>=2.1.2",
    "pandas>=2.2.3",
    "scipy>=1.15.3",
    "anndata>=0.11.4",
    "seaborn>=0.13.2",
    "matplotlib>=3.10.0",
]

[project.urls]
Homepage = "https://github.com/hwr9912/SCINApy"
Repository = "https://github.com/hwr9912/SCINApy.git"

[tool.setuptools.package-data]
SCINApy = ["data/*.csv", "data/*.json"]

[tool.setuptools]
include-package-data = true
packages = ["SCINApy"]