[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "onedevcommonmsgraph"
version = "1.0.3"
description = "Biblioteca para integração com Microsoft Graph API"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Marcus Simas", email = "marcus.simas@ufly.com.br" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.31.0",
    "msal>=1.25.0",
]

[project.urls]
"Homepage" = "https://github.com/onedev/onedev-common-ms-graph"
"Repository" = "https://github.com/onedev/onedev-common-ms-graph.git"
"Documentation" = "https://github.com/onedev/onedev-common-ms-graph#readme"

[tool.hatch.build.targets.wheel]
packages = ["onedevcommonmsgraph"] 