[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "embedded-text"
version = "0.0.1"
description = "Tool for extracting embedded text data in python script."
dependencies = []
readme = "README.rst"
requires-python = ">=3.9"

license = { file = "LICENSE" }
keywords = ["template", "development"]

authors = [{ name = "Nanigashi Uji", email="53845049+nanigashi-uji@users.noreply.github.com" },
           { name = "Nanigashi Uji", email="4423013-nanigashi_uji@users.noreply.gitlab.com" }]
           
maintainers = [{ name = "Nanigashi Uji", email="53845049+nanigashi-uji@users.noreply.github.com" },
           { name = "Nanigashi Uji", email="4423013-nanigashi_uji@users.noreply.gitlab.com" }]
           

classifiers = [
  'Development Status :: 2 - Pre-Alpha',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.9',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: 3.12',
  'Programming Language :: Python :: 3.13',
  'Topic :: Software Development',
  'Topic :: Utilities',
]

#dependencies = []

[project.urls]
Homepage = "https://github.com/nanigashi-uji/embedded-text"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
embedded_text = "embedded_text.embedded_text:main"

#[tool.setuptools.package-data]
#"yourlib" = ["share/data/*"]
