[build-system]
requires = ["setuptools", "wheel", "twine", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "monitoring-websocket-server"
version = "1.0.83.79"
description = "Real-Time WebSocket Monitoring System"
readme = "README.md"
requires-python = ">=3.8"
license = "GPL-3.0-or-later"
authors = [
    {name = "NMicInvest", email = "accueil@nmicinvest.com"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: System :: Monitoring",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "websockets", "psutil", "pyyaml", "colorama", "GPUtil", "nvidia-ml-py3", "pynvml"
]

[project.urls]
"Homepage" = "https://github.com/Nmicinvest/monitoring-websocket-server/"
"Repository" = "https://github.com/Nmicinvest/monitoring-websocket-server/"
"Bug Tracker" = "https://github.com/Nmicinvest/monitoring-websocket-server/issues"

[project.scripts]
monitoring-websocket-server = "run_server:main"

[tool.setuptools]
packages = ["alerts", "core", "exporters", "monitors", "services", "utils"]
py-modules = ["__init__", "config", "run_server"]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["requirements.txt"]
