[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "file-swirl"
version = "0.0.11"  # â† Bump this on each release
description = "A fast, flexible file sorter and organizer"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
  { name = "Nishant Ghanate" }
]
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "setuptools",
    "ExifRead==3.0.0",
    "pytest==8.4.1",
    "colorlog==6.9.0"
]

[project.urls]
Homepage = "https://github.com/NishantGhanate/FileSwirl"
Documentation = "https://github.com/NishantGhanate/FileSwirl#readme"
Source = "https://github.com/NishantGhanate/FileSwirl"
Tracker = "https://github.com/NishantGhanate/FileSwirl/issues"

[project.scripts]
file-sort = "file_swirl.cli:main"

[tool.setuptools.packages.find]
where = ["."]
